### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-express/purescript-express#102]
@nkly Do you still maintain this project?
There are a few pull requests that would need some love. I can offer to help here if you need any.

**Comment by nkly** [comment]
Hi @i-am-the-slime,

Yep, I'm still the official maintainer, but I've lost interest in the project sometime ago and stopped tracking Purescript progress in general. I'd be glad if somebody could pick it up and I'm happy to discuss the details of handover.

**Comment by srghma** [comment]
@nkly I could take that role

not sure how much time I could afford for this project, but I could merge important prs and later make a github action to push to pursuit on the new version tag

my pr https://github.com/nkly/purescript-express/pull/105

**Comment by nkly** [comment]
Hi @srghma,

Glad to hear that. 

If you still up to it, then I will deprecate this repo and corresponding package on Pursuit, and put a link to your fork as a recommended successor. There you can proceed developing it.

Could you please confirm that you're still want to do it and give me a link to the repo where you're going to continue development?

Thanks!

**Comment by srghma** [comment]
@nkly hi

I have created an org https://github.com/purescript-express and added you and @i-am-the-slime to maintainers

could you please confirm invitation and transfer this repo to https://github.com/purescript-express organisation to preserve all open issues and prs

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by srghma** [comment]
@nkly tnx!
