### ISSUE TITLE
Update to 0.14

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-express/purescript-express#109]
Should be clear.

Currently blocked by this:
https://github.com/paf31/purescript-foreign-generic/pull/61

**Comment by srghma** [comment]
@i-am-the-slime I have sent you an owner invitation to this org :)

**Comment by i-am-the-slime** [comment]
I'm too stupid to find it.

**Comment by i-am-the-slime** [comment]
Finally made it 😄

**Comment by ad-si** [comment]
@i-am-the-slime The generics PR is merged. What are the next steps?

**Comment by i-am-the-slime** [comment]
@ad-si Only seen this now but looks like @srghma has taken care already 🥳

**Comment by srghma** [comment]
I will tag new version and make a pr to package-sets
