### ISSUE TITLE
Add middleware to specific handlers

### ISSUE THREAD

**Issue by chexxor** [purescript-express/purescript-express#55]
I need to add a middleware function to a specific path.

The JS express lib I'm using says to do this:

``` javascript
app.get('/secret', thirdPartyExpressLib.loginRequired, function (req, res) {
  /*
    If we get here, the user is logged in.  Otherwise, they
    were redirected to the login page
   */
  res.send('Hello, ' + req.user.fullname);
});
```

This express wrapper doesn't have any way to add a middleware function like this to a specific path, however. The only way to do this is to modify purescript-express to add another param to `getWithMiddleware` to make it like `getWithMiddleware :: forall e r. (RoutePattern r) => r -> Handler e -> Handler e -> App e` ?

Or can I use Apply instance of Handler to collapse these two handlers into one and use the existing `get` function?

**Comment by dancingrobot84** [comment]
I think you can use `Monad` instead of `Apply`. For example:

```purescript
loginRequired :: Handler e
showSensitiveData :: Handler e

setupApp = do
  get "/show-sensitive-data" (loginRequired >>= \_ -> showSensitiveData)
```

The only problem is that, most probably, third-party middleware will only call next error handler in chain and not throw any exception, so the 2nd action won't notice anything and will be executed anyway. It can be fixed by installing an error handler that throws the exception further:

```purescript
errorHandler err = do
  -- Assuming that middleware has already sent 403 to the user
  liftEff $ throwException err

setupApp = do
  get "/show-sensitive-data" (loginRequired >>= \_ -> showSensitiveData)
  ...
  useOnError errorHandler
```

**Comment by chexxor** [comment]
@dancingrobot84 Thanks so much for the idea! I have gotten sidetracked with other stuff, but I'll get back to my express app soon to try this.

**Comment by chexxor** [comment]
The monad composition works, but the second one will be executed despite the first middleware calling "next" with an error. In addition, `(loginRequired >>= \_ -> showSensitiveData)` is considered a single middleware handler by Express, so your idea of bypassing the `showSensitiveData` function by attaching `useOnError errorHandler` wouldn't work, I believe.

I got around this by wrapping the `loginRequired` middleware function, then checking the `res` after it executes to see if it has a `401` response code and throwing an Exception there. I feel it's super hacky, but I am so frustrated with this that I just can't work on it anymore. It works in this case because this middleware ends the response when I want to terminate the request.

```
foreign import _loginRequired :: forall e. Request -> Response -> (ExpressM e Unit) -> (ExpressM e Unit)

loginRequired :: forall e. Handler e
loginRequired = HandlerM \req resp next ->
    liftEff $ _loginRequired req resp next

exports._loginRequired = function(req) {
  return function(res) {
    return function(next) {
      return function() {
        var r = middleware.authenticationRequired(req, res, next);
        if (res.statusCode == 401) {
          // Throwing a JavaScript exception
          throw new Error('Unauthorized...');
        }
      };
    };
  };
}
```

**Comment by dancingrobot84** [comment]
Yes, you're right about `errorHandler`, it doesn't work. However, looking at your PR and express.js code, I came up to another solution: you can just attach several middlewares using several calls to `get`. Here is the code to illustrate it:

```purescript
module EmbedApp where

import Prelude hiding (apply)
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Class (liftEff)
import Control.Monad.Eff.Console (CONSOLE(), log)
import Control.Monad.Eff.Exception (Error, error, message)
import Data.Maybe (Maybe(..), fromMaybe)
import Node.Express.Types (EXPRESS, ExpressM, Application)
import Node.Express.App (App, get, listenHttp, useOnError)
import Node.Express.Handler (Handler, nextThrow, next)
import Node.Express.Request(getQueryParam)
import Node.Express.Response (sendJson, setStatus)


loginRequired :: forall e. Handler e
loginRequired = do
  username <- getQueryParam "username"
  case username of
      Just "john-doe" -> next
      _ -> nextThrow $ error "UNAUTHORIZED"

showSensitiveData :: forall e. Handler (console :: CONSOLE | e)
showSensitiveData = do
  liftEff $ log "SHOWING SENSITIVE DATA"
  sendJson { username: "john-doe", password: "password" }

errorHandler :: forall e. Error -> Handler e
errorHandler err = do
  setStatus 400
  sendJson {error: message err}

app :: forall e. App (console :: CONSOLE | e)
app = do
  get "/showSensitiveData" (loginRequired)
  get "/showSensitiveData" (showSensitiveData)
  useOnError errorHandler

main = do
  listenHttp app 8080 \_ -> log $ "Listening on 8080"
```

Does it solve the problem you have?

**Comment by chexxor** [comment]
It's a good idea! I'll look closer and try it.

**Comment by chexxor** [comment]
@dancingrobot84 - Nice! Yeah that seems to work. It makes my server a bit more unmaintainable because I have to bind to the same route multiple times - I imagine in the future I might change the order of my routes and mistakenly place the login middleware *after* the route it is meant to protect. I'm fine with this, though, as ordering seems to be the nature of middleware.

Want me to close my other PR?

**Comment by chexxor** [comment]
Or add docs somewhere?

**Comment by dancingrobot84** [comment]
@chexxor Let's close the PR, but leave the issue open because calling several `get`s on the same route doesn't look good. I'll come up with a better way to handle the case of several chained handlers.

**Comment by chexxor** [comment]
One idea I had when considering this was making instance of monoid for HTTP verbs, but that would require changing data types quite a bit. (also, I choose monoid b/c it's one of the few concepts I know :3 )

```
newtype Route = Route String
data Get r e = Get (Route r) [Handler e]

instance monoidGet :: Monoid (Get r) where
  append (Get r1 h1s) (Get r2 h2s)
    = Get r1 (h1s <> h2s)
        -- requires r1 == r2, but idk how to type that
```

**Comment by i-am-the-slime** [comment]
So what's the status here?

**Comment by chexxor** [comment]
Probably needs someone to propose a concrete way to do it.

**Comment by i-am-the-slime** [comment]
I was wondering if the "use the same route twice" solution isn't good enough, given that one could write something like this:
```purescript
get2 path handler1 handler2 = do
  get path handler1
  get path handler2
```
But I probably misunderstood something.
```

**Comment by srghma** [comment]
can this be closed @chexxor ?

**Comment by chexxor** [comment]
@srghma Yeah! Thanks for the message!
