### ISSUE TITLE
Update Bower with latest commit?

### ISSUE THREAD

**Issue by RAbraham** [purescript-express/purescript-express#91]
First of all, thank you for updating to 0.12!

New to Bower here, but do you need to update the bower repository with the latest commit(`6bbda`  i.e. `Merge pull request #90 from adamczykm/bower-deps-fix`).

Otherwise, following the README and doing just a `bower install purescript-express` does not work for me. To build successfully, I had to manually do 
```bash
bower install purescript-aff
bower install purescript-test-unit
```
basically, the commit by `adamczykm`

**Comment by Thimoteus** [comment]
There needs to be a new release; so a new tag.

**Comment by srghma** [comment]
bower removed
