### ISSUE TITLE
cookieParser issue

### ISSUE THREAD

**Issue by AndreiChugunov** [purescript-express/purescript-express#94]
You have to not only `npm install express`, but to `npm install cookie-parser` as well since you will get a error trying to `use cookie-parser` (at least for express version 4.15.2).

**Comment by nkly** [comment]
Hi! Thank you for reporting this. Does it occur only when using `CookieParser` middleware or also in general? I'm trying to figure out where to put the information about `cookie-parser` dependency.

**Comment by AndreiChugunov** [comment]
@nkly 
This occurs only while using `CookieParser`. May be nodejs express had `cookie-parser` in it automatically some time ago and now they both just come as a separated packages (not sure on this, just my own guess). I think you can update readme ("Usage part").
